#docker run -d -p --name frontend/backend/mysql --network expense frontend:v1.0.0
name: expense
networks:
  default:
    name: expense
volumes:
  name: expense
services:
  mysql:
    image: mysql:v1.0.0
    container_name: mysql
    volumes:
      - source: mysql
        target: /var/lib/mysql
        type: volume
  backend:
     image: backend:v1.0.0
     container_name: backend
     command: sh -c "sleep 20 && node /app/index.js"

  frontend:
     image: frontend:v1.0.0
     container_name: frontend


